name:  Licenta Test workflow
on: workflow_dispatch
jobs:
    ec2-deploy:
        name: EC2 Instance deployment
        runs-on: [self-hosted, X64, Linux, runner-vm]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Terraform Init
              working-directory: ./terraform
              run: terraform init -input=false

            - name: Terraform Plan
              working-directory: ./terraform
              run: terraform plan -input=false -no-color -parallelism=1

            - name: Terraform Apply
              working-directory: ./terraform
              run: terraform apply -input=false -auto-approve -parallelism=1
                  
            - name: Docker build and push
              run: |
               docker build -t andreir76/licenta-test .
               docker push andreir76/licenta-test